name = "refsus-api"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "api.refsus.nauraki.com", custom_domain = true }
]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "refsus-db"
database_id = "4e0c687b-e9b2-428b-a4c7-8371532a1e2d"
migrations_dir = "migrations"
